### ISSUE TITLE
验证码的问题

### ISSUE THREAD

**Issue by kxltsuper** [darkhandz/BaiduLoginWithTiebaSignin#1]
我看您的程序是要手动输入验证码，这样还是不便利。能不能用手动登陆一次百度，获得cookie，然后以后用cookie登陆百度，跳过账号、密码和验证码这一系列的过程？

**Comment by darkhandz** [comment]
@kxltsuper 确实是手动输入验证码。
流程是这样的：
1. 不带参数执行脚本的时候，脚本默认是搜索已登录用户的cookie，然后进行自动签到，若未找到已登录用户，提示“无登录用户，退出”，代码片段见[这里](https://github.com/darkhandz/BaiduLoginWithTiebaSignin/blob/master/tieba_signin_server.py#L518-L523)。
2. 带参数`-l`执行脚本时，进入登录流程，需要验证码则手动输入，完成登录，保存cookie到脚本目录，退出。

所以，部署到服务器前，建议现在本地用`-l`参数逐个登录贴吧用户，然后再把脚本和cookie文件一起上传到服务器，服务器设置定期执行脚本（不带参数），就可以实现自动签到了，具体请参考我博客描述。目前我已连续签到62天了😬

**Comment by kxltsuper** [comment]
@darkhandz 谢谢回复，比如我有A 、B 、C三个百度账号，依次在本地登录。然后将脚本和所有cookie一起上传到服务器中并运行代码，我看了下代码，是不是实现了三个账号的依次签到？

**Comment by darkhandz** [comment]
[是的](https://github.com/darkhandz/BaiduLoginWithTiebaSignin/blob/master/tieba_signin_server.py#L499-L500)，其实你大可以在本地不带参数运行一次试试先😎

部署可以参考我的[博客文章](http://darkhandz.com/2017/05/13/%E7%99%BE%E5%BA%A6%E7%99%BB%E5%BD%95%E4%B8%8E%E8%B4%B4%E5%90%A7%E7%AD%BE%E5%88%B0/#部署)

**Comment by kxltsuper** [comment]
@darkhandz 正在用pycharm运行，但有错误。请问python是2.7还是3呢？另外，我已经python setup install 了PyExecJS-1.4.0，但在程序中import execjs时仍然显示没有找到这个execjs模块...

**Comment by kxltsuper** [comment]
@darkhandz 谢谢，正在拜读。现在百度登陆比想象中要复杂的多。

**Comment by darkhandz** [comment]
python3的，你看我repo的说明里命令也是python3的。
我这边开发环境是用macOS 10.12，直接`sudo /usr/local/python3/bin/pip3 install PyExecJS`安装的PyExecJS。部署到服务器也是同样的命令。
我对加密不了解，否则大概可以用其他python代码来代替那段JS，从而摆脱PyExecJS和Nodejs

**Comment by kxltsuper** [comment]
@darkhandz 已经测试成功，真厉害黑手。

**Comment by darkhandz** [comment]
Enjoy yourself~
